import os
import subprocess
import pathlib
import json

REPOS_SDK_GEN = "https://github.com/PlayFab/SDKGenerator"
REPOS_SDK_TPL = "https://github.com/MizunagiKB/PlayFab_GDScriptTemplate"
REPOS_SDK_API = "https://github.com/PlayFab/API_Specs"


def pre_build():

    work_dir = pathlib.Path("SDKGenerator")
    if work_dir.exists():
        os.chdir("SDKGenerator")
        subprocess.check_output(["git", "pull", REPOS_SDK_GEN])
        os.chdir("..")
    else:
        subprocess.check_output(["git", "clone", REPOS_SDK_GEN])

    os.chdir("SDKGenerator/privateTemplates")
    work_dir = pathlib.Path("gdscriptsdk")
    if work_dir.exists():
        os.chdir("gdscriptsdk")
        subprocess.check_output(["git", "pull", REPOS_SDK_TPL])
        os.chdir("..")
    else:
        subprocess.check_output(["git", "clone", REPOS_SDK_TPL, "gdscriptsdk"])
    os.chdir("../..")

    work_dir = pathlib.Path("API_Specs")
    if work_dir.exists():
        os.chdir("API_Specs")
        subprocess.check_output(["git", "pull", REPOS_SDK_API])
        os.chdir("..")
    else:
        subprocess.check_output(["git", "clone", REPOS_SDK_API])

    #
    os.chdir("SDKGenerator")
    subprocess.check_output(["sh", "SDKBuildScripts/initejs.sh"])
    os.chdir("..")

    #
    with open("API_Specs/SdkManualNotes.json", "r") as rf:
        dict_notes = json.load(rf)
        dict_notes["sdkVersion"]["gdscriptsdk"] = dict_notes["sdkVersion"]["pythonsdk"]

    with open("API_Specs/SdkManualNotes.json", "w") as wf:
        dict_notes = json.dump(dict_notes, wf)


def run_build():

    print(os.getcwd())
    work_dir = pathlib.Path("SDKGenerator")
    if work_dir.exists():
        os.chdir("SDKGenerator")
        subprocess.check_output(
            [
                "node",
                "generate.js",
                "gdscriptsdk=../PlayFab_GDScriptSdk",
                "-apiSpecPath",
                "../API_Specs",
            ]
        )
        os.chdir("..")


def epi_build():
    pass


pre_build()
run_build()
epi_build()
